# Generated by Django 5.2.8 on 2025-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_passwordresetcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=48),
        ),
    ]
