# Generated by Django 5.2.8 on 2025-11-17 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_news_alter_expense_text_alter_income_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'هزینه', 'verbose_name_plural': 'هزینه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'درآمد', 'verbose_name_plural': 'درآمدها'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcodes',
            options={'verbose_name': 'کد بازیابی رمز', 'verbose_name_plural': 'کدهای بازیابی رمز'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'توکن', 'verbose_name_plural': 'توکن\u200cها'},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-date'], name='expense_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='expense_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', '-date'], name='income_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['-date'], name='income_date_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-date'], name='news_date_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcodes',
            index=models.Index(fields=['code'], name='pwd_reset_code_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcodes',
            index=models.Index(fields=['email', 'time'], name='pwd_reset_email_time_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token'], name='token_idx'),
        ),
    ]
