# Generated by Django 5.2.8 on 2025-11-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_expense_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
