# Generated by Django 5.2.8 on 2025-11-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcodes',
            options={'verbose_name': 'Password Reset Code', 'verbose_name_plural': 'Password Reset Codes'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
    ]
